# Generated by Django 5.0.6 on 2024-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profession',
            field=models.CharField(default='Cricketer', max_length=50),
        ),
    ]
