# Generated by Django 5.0.6 on 2024-05-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_avatar_img_alter_profile_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='avatar_img',
            field=models.ImageField(default='biology.jpg', upload_to='blog/AvatarImg'),
        ),
    ]
