# Generated by Django 5.0.6 on 2024-05-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_avatar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Gmail_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
