# Generated by Django 5.0.6 on 2024-05-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_gmail_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.ImageField(default='business.png', upload_to='blog/AvatarImg')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('blogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
