# Generated by Django 5.0.6 on 2024-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(default='biology.jpg', upload_to='blog/coverImg'),
        ),
    ]
