# Generated by Django 5.0.6 on 2024-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
