# Generated by Django 5.0.6 on 2024-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blog_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments_written',
            field=models.IntegerField(default=0),
        ),
    ]
