# Generated by Django 5.0.6 on 2024-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_profile_comments_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Likes_given',
            field=models.IntegerField(default=0),
        ),
    ]
