# Generated by Django 5.0.6 on 2024-05-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_profile_likes_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(default='business.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(default='business.png', upload_to='images/'),
        ),
    ]
