# Generated by Django 5.0.6 on 2024-07-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_facebook_id_profile_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='student_Id',
            new_name='student_id',
        ),
    ]
