# Generated by Django 5.0.6 on 2024-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_rename_department_blog_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_you',
            field=models.TextField(default='i am a blogger'),
        ),
    ]
